(define (last-char str)
  (if (string? str)
      (if (< 0 (string-length str))
          (string-ref str (- (string-length str) 1))
          (integer->char 0))
      (integer->char 0)))

(define (first-char str)
  (if (string? str)
      (if (< 0 (string-length str))
          (string-ref str 0)
          (integer->char 0))
      (integer->char 0)))

(define (ends-with-slash? pathstr)
  (char=? (last-char pathstr) #\/))

(define (begins-with-slash? pathstr)
  (char=? (first-char pathstr) #\/))

(define (basename path)
  (let ((filename (car (reverse (string-split path #\/)))))
    (car (string-split filename #\.))))

(define (path-join basedir . extra)
  (let iter ((stack (list basedir))
             (e extra))
    (cond ((null? e)
            (join "" (reverse stack)))
          ((null? (car e))
            (join "" (reverse stack)))
          ((and (ends-with-slash? (car stack))
                (begins-with-slash? (car e)))
            (iter (cons (substring (car e) 1) stack) (cdr e)))
          ((ends-with-slash? (car stack))
            (iter (cons (car e) stack) (cdr e)))
          (else
            (iter (cons (car e) (cons "/" stack)) (cdr e))))))
