(define-library (presto http)
  (import (scheme base)
          (chibi)
          (chibi show)
          (chibi io)
          (chibi net)
          (chibi term edit-line)
          (chibi process)
          (chibi string)
          (chibi filesystem)
          (chibi log)
          (presto parse)
          (presto testsuite)
          (presto mime))
  (export http-server join http-set-access-log! http-set-error-log!)
  (include "http.scm"))
