(define (make-request method path proto headerset)
  (let ((method method)
        (path path)
        (proto proto)
        (headers headerset)
        (basedir #f)
        (arguments '())
        (body #f))
    (define (get-method) method)
    (define (get-proto) proto)
    (define (set-path! arg) (set! path arg))
    (define (get-path) path)
    (define (set-basedir! arg) (set! basedir arg))
    (define (get-basedir) basedir)
    (define (get-headers) headers)
    (define (get-header header)
      (let ((data (assq header headers)))
        (if (pair? data) (cdr data) #f)))
    (define (set-body! arg) (set! body arg))
    (define (get-body) body)

    (let ((elements (string-split path #\? 2)))
      (if (>= 2 (length elements))
        (set! path (car elements))
        (set! arguments (car (cdr elements)))))

    (lambda (dispatch . args)
      (cond ((eq? dispatch 'get-method)
              (apply get-method args))
            ((eq? dispatch 'get-proto)
              (apply get-proto args))
            ((eq? dispatch 'set-path!)
              (apply set-path! args))
            ((eq? dispatch 'get-path)
              (apply get-path args))
            ((eq? dispatch 'set-basedir!)
              (apply set-basedir! args))
            ((eq? dispatch 'get-basedir)
              (apply get-basedir args))
            ((eq? dispatch 'get-headers)
              (apply get-headers args))
            ((eq? dispatch 'get-header)
              (apply get-header args))
            ((eq? dispatch 'set-body!)
              (apply set-body! args))
            ((eq? dispatch 'get-body)
              (apply get-body args))
            (else
              (display "make-request dispatch fallthrough\n"
                       (current-error-port))
              '())))))
