(define-library (presto testsuite)
  (import (scheme small)
          (srfi 1)
          (chibi)
          (chibi string)
          (chibi time)
          (chibi filesystem)
          (chibi ast))
  (export testsuite)
  (include "testsuite.scm"))
